location /cloth/ {
    alias /var/www/cloth-agent/;
    index index.html;
    try_files $uri $uri/ /cloth/index.html;
}

location = /cloth {
    return 301 /cloth/;
}

location /cloth-api/ {
    proxy_pass http://139.224.226.80:8080/api/;
    proxy_http_version 1.1;
    proxy_set_header Host 139.224.226.80;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 180s;
    client_max_body_size 12m;
}
